bind_host: 0.0.0.0
bind_port: 80
users:
- name: admin
  password: $2a$10$8xckhp5mxgrxa7ez/8FvOee54.B9UkldwfIUQ/RryCixy/gxLKzfO
language: ""
rlimit_nofile: 0
web_session_ttl: 720
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 30
  querylog_enabled: true
  querylog_interval: 1
  querylog_memsize: 0
  protection_enabled: true
  blocking_mode: null_ip
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 9.9.9.9
  - 149.112.112.112
  all_servers: true
  edns_client_subnet: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  cache_size: 4194304
  upstream_dns:
  - https://dns.quad9.net/dns-query
  filtering_enabled: true
  filters_update_interval: 72
  parental_sensitivity: 0
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: '*.minhluc.info'
    answer: 127.0.0.1
  blocked_services: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://abpvn.com/vip/lucndm.txt
  name: ABPVN List (VIP) [90p9.tv]
  id: 1579944643
- enabled: true
  url: https://raw.githubusercontent.com/nmtrung/FMSF-2.0/master/fmsf_2.0.txt
  name: FMSF 2
  id: 1579944644
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients:
- name: adguard
  ids:
  - 172.16.10.100
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams: []
- name: logdna
  ids:
  - 172.16.10.2
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams: []
- name: t480s
  ids:
  - 172.16.10.1
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams: []
log_file: ""
verbose: false
schema_version: 6
